In [1]:
import os
import sys
sys.path.append("..")

from copy import deepcopy
import random
import pandas as pd
import numpy as np

from src.Environment.tic_tac_toe import TicTacToe
from src.Agent.mcts import Node
from src.Agent.mcts import MCTS

In [2]:
game = TicTacToe(player=1)
best_child = Node(TicTacToe(player=1))
while game.metadata['terminated']==False:
    print(game)
    mcts = MCTS(best_child)
    mcts.main()
    best_move, best_child = best_child.get_best_child()
    game.make_move(best_move[0], best_move[1])

print(game)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]

[0. 0. 0.]
[0. 1. 0.]
[0. 0. 0.]

[0. 0. 0.]
[0. 1. 0.]
[0. 2. 0.]

[0. 0. 0.]
[0. 1. 0.]
[1. 2. 0.]

[0. 2. 0.]
[0. 1. 0.]
[1. 2. 0.]

[1. 2. 0.]
[0. 1. 0.]
[1. 2. 0.]

[1. 2. 0.]
[2. 1. 0.]
[1. 2. 0.]

[1. 2. 1.]
[2. 1. 0.]
[1. 2. 0.]

